inherits:
    - strictness_medium
    - full_pep8

pylint:
  disable:
    - C0103
    - C0325
    - R0913
    - W0621
  options:
    generated-members: __globals__
    ignored-modules: pytest

pep8:
  options:
    max-line-length: 79
